server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/batchdb
    username: postgres
    password: rms@db

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: "always"

app:
  openapi:
    local-url: http://localhost:8088